name: route_store
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  flutter_screenutil: ^5.8.4
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.1.12
  intl: ^0.19.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.10
  rename: ^3.0.1
  dartz: ^0.10.1
  pin_code_fields: ^8.0.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2



  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800